### ISSUE TITLE
Rendering broken on ios

### ISSUE THREAD

**Issue by jwildeboer** [RedHatOfficial/RedHatOfficial.github.io#112] opened 2018-03-24 23:48 UTC
When I open the page, it looks like in attached screenshot. iOS 11.2 on iPhone 8. 
![f8315521-52c3-4236-afc0-34cb52d7dc76](https://user-images.githubusercontent.com/873028/37870138-4207a31a-2fc6-11e8-916a-06528f851fa8.jpeg)

**Comment by castastrophe** [comment] 2018-03-25 14:05
This is a dupe of a previously opened issue and addressed in PR: https://github.com/RedHatOfficial/RedHatOfficial.github.io/pull/104

**Closed by castastrophe** 2018-03-25 14:05 UTC
